"""Create digital_assets table

Revision ID: fef5a9f964e2
Revises: 3ebc9429be8a
Create Date: 2025-07-02 09:36:35.131201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef5a9f964e2'
down_revision: Union[str, Sequence[str], None] = '3ebc9429be8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digital_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_assets_id'), 'digital_assets', ['id'], unique=False)
    op.create_index(op.f('ix_digital_assets_name'), 'digital_assets', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digital_assets_name'), table_name='digital_assets')
    op.drop_index(op.f('ix_digital_assets_id'), table_name='digital_assets')
    op.drop_table('digital_assets')
    # ### end Alembic commands ###
